#spring.application.name=ShopApp
server:
  port: 8088
spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ${MYSQL_ROOT_PASSWORD:HunG1907@}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    flyway:
        locations: classpath:/db/migration, classpath:/dev/db/migration
        baseline-on-migrate: true
        baseline-version: 0
    data:
      redis:
        host: ${REDIS_HOST:localhost} 
        port: ${REDIS_PORT:6379}  
    
    messages:
      basename: i18n/messages
      encoding: UTF-8
      default-locale: en
api:
    prefix: /api/v1
    
jwt:
    # 1h
    expiration: 3600 
    secretKey: WGBtsEm/cGzeh2xfNitX7F5fTZpCHdy1wp60rTzJOpA=

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"
    
    
